---@meta
error('cannot require a meta file')

---@class info.parser.Position
---@field start integer
---@field end_ integer

---@class info.parser.TextPosition : info.parser.Position
---@field text string

---@class info.parser.Header.Pair : info.parser.Position
---@field value info.parser.TextPosition

---@class info.parser.Reference : info.parser.Position
---@field type info.Element
---@field label info.parser.TextPosition
---@field target? info.parser.TextPosition

---@class info.parser.Header
---@field file info.parser.Header.Pair
---@field node info.parser.Header.Pair
---@field next? info.parser.Header.Pair
---@field prev? info.parser.Header.Pair
---@field up? info.parser.Header.Pair

---Captures generated by parsing the manual's content.
---@class info.parser.Captures
---@field header info.parser.Header
---@field elements info.parser.Reference[]

---
--- Final manual data stored in `vim.b._info_manual`
---

---Position of a single character in a buffer.
---Uses (1, 0) indexing for `line` and `col` respectively.
---@class info.CharPosition
---@field line integer 1-indexed
---@field col integer 0-indexed

---Position of a piece of text in a buffer.
---The format of `start` and `end_` make it seamless to test if the cursor
---is contained withing the text using the returned value of `nvim_win_get_cursor()`.
---The range is end-inclusive to make is easier to use in Lua and with the extmarks API.
---@class info.TextRange
---@field start info.CharPosition
---@field end_ info.CharPosition

---@class info.Manual.Target
---@field file string
---@field node string

---@class info.Manual.Node : info.TextRange
---@field target info.Manual.Target

---@class info.Manual.XRef : info.TextRange
---@field label string
---@field target info.Manual.Target

---@class info.Manual.Relations
---@field next? info.Manual.Node
---@field prev? info.Manual.Node
---@field up? info.Manual.Node

---Data of an Info manual rendered in a buffer.
---@class info.Manual
---@field file string
---@field node string
---@field relations info.Manual.Relations
---@field xreferences info.Manual.XRef[]
---@field menu_entries info.Manual.XRef[]
